<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AuthHelpers\**" />
    <Compile Remove="Extensions\**" />
    <Content Remove="AuthHelpers\**" />
    <Content Remove="Extensions\**" />
    <EmbeddedResource Remove="AuthHelpers\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <None Remove="AuthHelpers\**" />
    <None Remove="Extensions\**" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.5" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.5" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.5" />
    <PackageReference Include="MudBlazor" Version="8.6.0" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\TechnicalService.Shared\TechnicalService.Shared.csproj" />
  </ItemGroup>

</Project>
