//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalService.Application.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReturnMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReturnMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnicalService.Application.Extensions.ReturnMessages", typeof(ReturnMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oluşturma.
        /// </summary>
        public static string Action_Create {
            get {
                return ResourceManager.GetString("Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to silme.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listeleme.
        /// </summary>
        public static string Action_List {
            get {
                return ResourceManager.GetString("Action_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Action_Password {
            get {
                return ResourceManager.GetString("Action_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre sıfırlama.
        /// </summary>
        public static string Action_PasswordReset {
            get {
                return ResourceManager.GetString("Action_PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token yenileme .
        /// </summary>
        public static string Action_RefreshToken {
            get {
                return ResourceManager.GetString("Action_RefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getirme.
        /// </summary>
        public static string Action_Retrieve {
            get {
                return ResourceManager.GetString("Action_Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to güncelleme.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        public static string EntityType_Brand {
            get {
                return ResourceManager.GetString("EntityType_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markalar.
        /// </summary>
        public static string EntityType_Brand_Plural {
            get {
                return ResourceManager.GetString("EntityType_Brand_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yasal Evrak.
        /// </summary>
        public static string EntityType_LegalDocument {
            get {
                return ResourceManager.GetString("EntityType_LegalDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yasal Evraklar.
        /// </summary>
        public static string EntityType_LegalDocument_Plural {
            get {
                return ResourceManager.GetString("EntityType_LegalDocument_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel.
        /// </summary>
        public static string EntityType_Personnel {
            get {
                return ResourceManager.GetString("EntityType_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personeller.
        /// </summary>
        public static string EntityType_Personnel_Plural {
            get {
                return ResourceManager.GetString("EntityType_Personnel_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string EntityType_Product {
            get {
                return ResourceManager.GetString("EntityType_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string EntityType_Product_Plural {
            get {
                return ResourceManager.GetString("EntityType_Product_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Türü.
        /// </summary>
        public static string EntityType_ProductType {
            get {
                return ResourceManager.GetString("EntityType_ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Türleri.
        /// </summary>
        public static string EntityType_ProductType_Plural {
            get {
                return ResourceManager.GetString("EntityType_ProductType_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri Numarası.
        /// </summary>
        public static string EntityType_SerialNumber {
            get {
                return ResourceManager.GetString("EntityType_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri Numaraları.
        /// </summary>
        public static string EntityType_SerialNumber_Plural {
            get {
                return ResourceManager.GetString("EntityType_SerialNumber_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis kaydı.
        /// </summary>
        public static string EntityType_ServiceRecord {
            get {
                return ResourceManager.GetString("EntityType_ServiceRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis kayıtları.
        /// </summary>
        public static string EntityType_ServiceRecord_Plural {
            get {
                return ResourceManager.GetString("EntityType_ServiceRecord_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis Adımı.
        /// </summary>
        public static string EntityType_ServiceRecordStep {
            get {
                return ResourceManager.GetString("EntityType_ServiceRecordStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis kaydı adımları.
        /// </summary>
        public static string EntityType_ServiceRecordStep_Plural {
            get {
                return ResourceManager.GetString("EntityType_ServiceRecordStep_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis kaydı adımı.
        /// </summary>
        public static string EntityType_ServiceRecordStep_Singular {
            get {
                return ResourceManager.GetString("EntityType_ServiceRecordStep_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik servis.
        /// </summary>
        public static string EntityType_TechnicalService {
            get {
                return ResourceManager.GetString("EntityType_TechnicalService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik servisler.
        /// </summary>
        public static string EntityType_TechnicalService_Plural {
            get {
                return ResourceManager.GetString("EntityType_TechnicalService_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        public static string EntityType_User {
            get {
                return ResourceManager.GetString("EntityType_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        public static string EntityType_User_Plural {
            get {
                return ResourceManager.GetString("EntityType_User_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı ürünü.
        /// </summary>
        public static string EntityType_UserProduct {
            get {
                return ResourceManager.GetString("EntityType_UserProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı ürünleri.
        /// </summary>
        public static string EntityType_UserProduct_Plural {
            get {
                return ResourceManager.GetString("EntityType_UserProduct_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; adında bir {1} zaten mevcut..
        /// </summary>
        public static string Error_Entity_AlreadyExists_WithName {
            get {
                return ResourceManager.GetString("Error_Entity_AlreadyExists_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bulunamadı..
        /// </summary>
        public static string Error_Entity_NotFound {
            get {
                return ResourceManager.GetString("Error_Entity_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belirtilen ID ile {0} bulunamadı..
        /// </summary>
        public static string Error_Entity_NotFound_ById {
            get {
                return ResourceManager.GetString("Error_Entity_NotFound_ById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem sırasında bir hata oluştu. {0}.
        /// </summary>
        public static string Error_Generic_OperationFailed {
            get {
                return ResourceManager.GetString("Error_Generic_OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} işlemi sırasında beklenmedik bir sunucu hatası oluştu. {1}.
        /// </summary>
        public static string Error_Generic_SimpleOperationFailed {
            get {
                return ResourceManager.GetString("Error_Generic_SimpleOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem sırasında beklenmedik bir sorun oluştu. Lütfen sistem yöneticinize başvurun..
        /// </summary>
        public static string Error_Generic_WithAdminContact {
            get {
                return ResourceManager.GetString("Error_Generic_WithAdminContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevcut şifre hatalı..
        /// </summary>
        public static string Error_InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("Error_InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} oluşturulurken sunucu tarafında bir hata oluştu. {1}.
        /// </summary>
        public static string Error_Operation_Create {
            get {
                return ResourceManager.GetString("Error_Operation_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} silinirken sunucu tarafında bir hata oluştu. {1}.
        /// </summary>
        public static string Error_Operation_Delete {
            get {
                return ResourceManager.GetString("Error_Operation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} listelenirken sunucu tarafında bir hata oluştu. {1}.
        /// </summary>
        public static string Error_Operation_List {
            get {
                return ResourceManager.GetString("Error_Operation_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} getirilirken sunucu tarafında bir hata oluştu. {1}.
        /// </summary>
        public static string Error_Operation_Retrieve {
            get {
                return ResourceManager.GetString("Error_Operation_Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} güncellenirken sunucu tarafında bir hata oluştu. {1}.
        /// </summary>
        public static string Error_Operation_Update {
            get {
                return ResourceManager.GetString("Error_Operation_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ürün için tamamlanmamış bir servis kaydı bulunmaktadır..
        /// </summary>
        public static string Error_ServiceRecord_IncompleteExists_ForProduct {
            get {
                return ResourceManager.GetString("Error_ServiceRecord_IncompleteExists_ForProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen daha sonra tekrar deneyiniz. Sorun devam ederse destek ekibi ile iletişime geçiniz..
        /// </summary>
        public static string Error_Support_Contact_Message {
            get {
                return ResourceManager.GetString("Error_Support_Contact_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz e-posta adresi başka bir kullanıcı tarafından kullanılmaktadır..
        /// </summary>
        public static string Error_User_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("Error_User_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğrulama bağlantısının süresi sona ermiştir. Lütfen yeni doğrulama bağlantısı alınız..
        /// </summary>
        public static string Error_User_TokenExpiredOrInvalid {
            get {
                return ResourceManager.GetString("Error_User_TokenExpiredOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu ürün başka bir kullanıcı tarafından kayıt edilmiştir. Eğer bunun bir hata olduğunu düşünüyorsanız lütfen destek ile iletişime geçin..
        /// </summary>
        public static string Error_UserProduct_AlreadyRegistered {
            get {
                return ResourceManager.GetString("Error_UserProduct_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz bilgiler kayıtlarımızla eşleşmiyor. Lütfen ürün bilgilerinizi kontrol ederek tekrar deneyiniz. Eğer bunun bir hata olduğunu düşünüyorsanız lütfen destek ile iletişime geçin..
        /// </summary>
        public static string Error_UserProduct_Mismatch {
            get {
                return ResourceManager.GetString("Error_UserProduct_Mismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-posta veya şifre hatalı.
        /// </summary>
        public static string Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı aktif değil.
        /// </summary>
        public static string Login_UserNotActive {
            get {
                return ResourceManager.GetString("Login_UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} başarıyla oluşturuldu..
        /// </summary>
        public static string Message_Success_Created {
            get {
                return ResourceManager.GetString("Message_Success_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; adlı {1} başarıyla oluşturuldu..
        /// </summary>
        public static string Message_Success_Created_WithName {
            get {
                return ResourceManager.GetString("Message_Success_Created_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} başarıyla silindi..
        /// </summary>
        public static string Message_Success_Deleted {
            get {
                return ResourceManager.GetString("Message_Success_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} başarıyla listelendi..
        /// </summary>
        public static string Message_Success_Listed {
            get {
                return ResourceManager.GetString("Message_Success_Listed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} başarıyla getirildi..
        /// </summary>
        public static string Message_Success_Retrieved {
            get {
                return ResourceManager.GetString("Message_Success_Retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} başarıyla güncellendi..
        /// </summary>
        public static string Message_Success_Updated {
            get {
                return ResourceManager.GetString("Message_Success_Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; adlı {1} başarıyla güncellendi..
        /// </summary>
        public static string Message_Success_Updated_WithName {
            get {
                return ResourceManager.GetString("Message_Success_Updated_WithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürününüz hesabınıza başarıyla eklendi..
        /// </summary>
        public static string Message_Success_UserProduct_Added {
            get {
                return ResourceManager.GetString("Message_Success_UserProduct_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz bilgiler kayıtlarımızla eşleşmiyor. Lütfen bilgilerinizi kontrol ederek tekrar deneyin..
        /// </summary>
        public static string Password_Reset_InfoMismatch {
            get {
                return ResourceManager.GetString("Password_Reset_InfoMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifreniz &apos;{0}&apos; e-posta adresinize gönderildi..
        /// </summary>
        public static string Password_Reset_SuccessEmailSent {
            get {
                return ResourceManager.GetString("Password_Reset_SuccessEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel başarıyla oluşturuldu. Giriş bilgileri personelin e-posta adresine gönderildi..
        /// </summary>
        public static string Personnel_Created_Success_And_EmailSent {
            get {
                return ResourceManager.GetString("Personnel_Created_Success_And_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu e-posta ile kayıtlı bir personel zaten mevcut..
        /// </summary>
        public static string Personnel_Email_Conflict {
            get {
                return ResourceManager.GetString("Personnel_Email_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu TC Kimlik Numarası ile kayıtlı bir personel zaten mevcut..
        /// </summary>
        public static string Personnel_Identity_Conflict {
            get {
                return ResourceManager.GetString("Personnel_Identity_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu dahili e-posta ile kayıtlı bir personel zaten mevcut..
        /// </summary>
        public static string Personnel_InternalEmail_Conflict {
            get {
                return ResourceManager.GetString("Personnel_InternalEmail_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personel rolü &quot;Kullanıcı&quot; olamaz!.
        /// </summary>
        public static string Personnel_Role_Conflict {
            get {
                return ResourceManager.GetString("Personnel_Role_Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz veya süresi dolmuş oturum. Lütfen tekrar giriş yapın..
        /// </summary>
        public static string RefreshToken_InvalidOrExpired {
            get {
                return ResourceManager.GetString("RefreshToken_InvalidOrExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumunuz yenilenirken bir sorun oluştu. Lütfen tekrar giriş yapınız. Eğer sorununuz devam ederse lütfen destek ile iletişime geçin..
        /// </summary>
        public static string RefreshToken_UnexpectedError {
            get {
                return ResourceManager.GetString("RefreshToken_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumunuz doğrulanamadı. Lütfen tekrar giriş yapın..
        /// </summary>
        public static string RefreshToken_VerificationFailed {
            get {
                return ResourceManager.GetString("RefreshToken_VerificationFailed", resourceCulture);
            }
        }
    }
}
