//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalService.Portal.Admin.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AdminMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AdminMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnicalService.Portal.Admin.Messages.AdminMessages", typeof(AdminMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu {0} silmek istediğinize emin misiniz?.
        /// </summary>
        internal static string Delete_Content {
            get {
                return ResourceManager.GetString("Delete_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silme işlemi sırasında bir hata meydana geldi!.
        /// </summary>
        internal static string Delete_ErrorMessage {
            get {
                return ResourceManager.GetString("Delete_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string Delete_SubmitButtonText {
            get {
                return ResourceManager.GetString("Delete_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos; {0} Başarılıyla Silindi.
        /// </summary>
        internal static string Delete_SuccessMessage {
            get {
                return ResourceManager.GetString("Delete_SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Sil: {1}.
        /// </summary>
        internal static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to markayı.
        /// </summary>
        internal static string EntityType_Brand_Singular_Accusative {
            get {
                return ResourceManager.GetString("EntityType_Brand_Singular_Accusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marka.
        /// </summary>
        internal static string EntityType_Brand_Singular_Nominative {
            get {
                return ResourceManager.GetString("EntityType_Brand_Singular_Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yasal belgeyi.
        /// </summary>
        internal static string EntityType_LegalDocument_Singular_Accusative {
            get {
                return ResourceManager.GetString("EntityType_LegalDocument_Singular_Accusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yasal Belge.
        /// </summary>
        internal static string EntityType_LegalDocument_Singular_Nominative {
            get {
                return ResourceManager.GetString("EntityType_LegalDocument_Singular_Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ürünü.
        /// </summary>
        internal static string EntityType_Product_Singular_Accusative {
            get {
                return ResourceManager.GetString("EntityType_Product_Singular_Accusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        internal static string EntityType_Product_Singular_Nominative {
            get {
                return ResourceManager.GetString("EntityType_Product_Singular_Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ürün türünü.
        /// </summary>
        internal static string EntityType_ProductType_Singular_Accusative {
            get {
                return ResourceManager.GetString("EntityType_ProductType_Singular_Accusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Türü.
        /// </summary>
        internal static string EntityType_ProductType_Singular_Nominative {
            get {
                return ResourceManager.GetString("EntityType_ProductType_Singular_Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seri numarasını.
        /// </summary>
        internal static string EntityType_SerialNumber_Singular_Accusative {
            get {
                return ResourceManager.GetString("EntityType_SerialNumber_Singular_Accusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seri Numarası.
        /// </summary>
        internal static string EntityType_SerialNumber_Singular_Nominative {
            get {
                return ResourceManager.GetString("EntityType_SerialNumber_Singular_Nominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teknik servisi.
        /// </summary>
        internal static string EntityType_TechnicalService_Singular_Accusative {
            get {
                return ResourceManager.GetString("EntityType_TechnicalService_Singular_Accusative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teknik Servis.
        /// </summary>
        internal static string EntityType_TechnicalService_Singular_Nominative {
            get {
                return ResourceManager.GetString("EntityType_TechnicalService_Singular_Nominative", resourceCulture);
            }
        }
    }
}
